parser:
  babel-eslint
env:
  node: true
  es6: true
  browser: true
plugins:
  - eslint-plugin-react
  - import
globals:
  window: true
settings:
    import/resolve:
      extensions:
      - .js
      - .jsx
    import/ignore: node_modules
    import/parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaFeatures:
    arrowFunctions: true
    binaryLiterals: true
    blockBindings: true
    classes: true
    defaultParams: true
    destructuring: true
    forOf: true
    generators: true
    globalReturn: true
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralDuplicateProperties: true
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    octalLiterals: true
    regexUFlag: true
    regexYFlag: true
    spread: true
    superInFunctions: true
    templateStrings: true
    unicodeCodePointEscapes: true
rules:
    sort-keys:
      - 2
      - asc
      -
        caseSensitive: false
    brace-style:
      - 2
      - stroustrup
      - allowSingleLine: true
    comma-dangle:
      - 2
      - always-multiline
    complexity:
      - 2
      - max: 9
    consistent-return:
      - 0
    constructor-super:
      - 2
    curly:
      - 2
    default-case:
      - 2
    dot-location:
      - 2
      - property
    dot-notation:
      - 2
    eol-last:
      - error
    eqeqeq:
      - 2
    import/default:
      - 2
    import/export:
      - 2
    import/first:
      - 2
    import/named:
      - 2
    import/no-duplicates:
      - 2
    import/no-mutable-exports:
      - 2
    import/no-unresolved:
      - 2
    import/order:
      - 2
    indent:
      - 2
      - 2
      - SwitchCase: 1
    jsx-quotes:
      - error
      - prefer-single
    keyword-spacing:
      - 2
    linebreak-style:
      - 2
      - unix
    max-depth:
      - 2
      - 3
    new-cap:
      - 2
    new-parens:
      - 2
    no-alert:
      - 2
    no-array-constructor:
      - 2
    no-caller:
      - 2
    no-console:
      - 2
    no-debugger:
      - 2
    no-div-regex:
      - 2
    no-dupe-args:
      - 2
    no-dupe-keys:
      - 2
    no-duplicate-case:
      - 2
    no-else-return:
      - 2
    no-eq-null:
      - 2
    no-eval:
      - 2
    no-ex-assign:
      - 2
    no-extend-native:
      - 2
    no-extra-bind:
      - 2
    no-extra-semi:
      - 2
    no-fallthrough:
      - 2
    no-implied-eval:
      - 2
    no-invalid-regexp:
      - 2
    no-invalid-this:
      - 2
    no-irregular-whitespace:
      - 2
    no-iterator:
      - 2
    no-labels:
      - 0
    no-lone-blocks:
      - 2
    no-lonely-if:
      - 2
    no-loop-func:
      - 2
    no-magic-numbers:
      - 2
      - ignore:
        - -1
        - 0
        - 1
        - 2
        - 1000
    no-mixed-requires:
      - 0
    no-mixed-spaces-and-tabs:
      - 2
    no-multi-spaces:
      - 2
    no-multi-str:
      - 2
    no-native-reassign:
      - 2
    no-negated-in-lhs:
      - 2
    no-nested-ternary:
      - 2
    no-new-func:
      - 2
    no-new-object:
      - 2
    no-new:
      - 2
    no-param-reassign:
      - 2
    no-proto:
      - 2
    no-redeclare:
      - 2
    no-return-assign:
      - 2
    no-self-compare:
      - 2
    no-sequences:
      - 2
    no-this-before-super:
      - 2
    no-throw-literal:
      - 2
    no-trailing-spaces:
      - 2
    no-undef:
      - 2
    no-underscore-dangle:
      - 0
    no-unexpected-multiline:
      - 2
    no-unneeded-ternary:
      - 2
    no-unreachable:
      - 2
    no-unsafe-finally:
      - 2
    no-unused-expressions:
      - 2
      -
        allowShortCircuit: true
        allowTernary: true
    no-unused-vars:
      - 2
      - args: none
    no-use-before-define:
      - error
      -
        functions: true
        classes: true
    no-useless-concat:
      - 2
    no-void:
      - 2
    no-with:
      - 2
    prefer-arrow-callback:
      - 2
    prefer-const:
      - 2
    prefer-template:
      - 2
    quotes:
      - 2
      - single
    react/jsx-indent:
      - 2
      - 2
    react/jsx-key:
      - 2
    react/jsx-no-bind:
      - 2
    react/jsx-no-duplicate-props:
      - 2
    react/jsx-tag-spacing:
      - 2
    react/no-string-refs:
      - 1
    react/jsx-wrap-multilines:
      - 2
    react/react-in-jsx-scope:
      - 2
    react/require-render-return:
      - 2
    react/self-closing-comp:
      - 2
    semi:
      - 2
    space-before-blocks:
      - 2
    space-before-function-paren:
      - 2
    space-in-parens:
      - 2
      - never
    space-infix-ops:
      - 2
    strict:
      - 2
      - never
    use-isnan:
      - 2
    valid-typeof:
      - 2
    wrap-iife:
      - 2
    yoda:
      - 2
      - never
    max-len:
      - 2
      - 200
